#ifndef __addon_h
#define __addon_h
#include <string>
#include <vector>
#include <node_api.h>
#include "active.h"
#include "CoreFoundation/CoreFoundation.h"
#include "CoreServices/CoreServices.h"
#include "arguments.h"
#include "caller_context.h"
#include "check.h"
#include "cpp_threadsafe_function.h"
#include "event.h"
#include "functions.h"
#include "threadsafe_function.h"
#include "worker.h"
#include "sleep_loop_worker.h"
#include "cf_worker.h"
#endif
